In [2]:
import torch

In [3]:
# requires_grad：指定是否需要求导

In [121]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [122]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
# y was created as a result of an operation, so it has a grad_fn.
# rad_fn 属性保存着创建了张量的 Function 的引用

In [ ]:
#Each tensor has a .grad_fn attribute that references a Function that has created the Tensor
#(except for Tensors created by the user - their grad_fn is None).

In [123]:
print(y.grad_fn)

In [126]:
z = y * y * 3
z1 = z * 3
out = z1.mean()

print(z,z1, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor([[81., 81.],
        [81., 81.]], grad_fn=<MulBackward0>) tensor(81., grad_fn=<MeanBackward0>)


In [127]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [128]:
a.requires_grad_(True)

tensor([[1.8313, 6.7348],
        [1.0256, 1.6025]], requires_grad=True)

In [228]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
c = a + b
d = c.sum()

False
True


In [229]:
c

tensor([[5.2301, 5.4677],
        [4.8100, 5.3372]], grad_fn=<AddBackward0>)

In [230]:
# 输出不是标量时需要设置其数组形状，数组中的数值与计算结果相乘
gradients = torch.tensor([[1, 1],[1, 1]], dtype=torch.float)

In [232]:
d.backward()

In [233]:
print(a.grad)

tensor([[ 9.1223, 11.0235],
        [ 5.7618,  9.9793]])


In [210]:
# print(b.grad)

In [25]:
#torch.randn:Returns a tensor filled with random numbers from a normal distribution

In [26]:
x = torch.randn(3, requires_grad=True)

y = x * 2

In [27]:
x

tensor([-0.6147, -0.5320, -0.9373], requires_grad=True)

In [28]:
y

tensor([-1.2295, -1.0640, -1.8747], grad_fn=<MulBackward0>)

## 最终通过sum将各个元素相加再计算梯度不影响结果，较为方便

In [41]:
a1 = torch.ones(2, 2, requires_grad=True)
a1

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [42]:
b1 = a1 * a1
b1

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

In [43]:
c1 = a1 + b1
c1

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [44]:
gradients = torch.tensor([[1, 1],[1, 1]], dtype=torch.float)

In [45]:
c1.backward(gradients)

In [46]:
a1.grad

tensor([[3., 3.],
        [3., 3.]])

In [47]:
a2 = torch.ones(2, 2, requires_grad=True)
b2 = a2 * a2
c2 = a2 + b2
d = c2.sum()

In [48]:
d.backward()

In [49]:
a1.grad

tensor([[3., 3.],
        [3., 3.]])

In [43]:
#torch.norm():求l2范数。

In [44]:
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-629.4823, -544.7878, -959.8306], grad_fn=<MulBackward0>)


In [47]:
y

tensor([-629.4823, -544.7878, -959.8306], grad_fn=<MulBackward0>)

In [45]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [54]:
x = torch.randn(3, requires_grad=True)

y = x * 2
gradients = torch.tensor([0.1, 1, 1], dtype=torch.float)

In [ ]:
# If you want to compute the derivatives, you can call .backward() on a Tensor. 
# If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), 
# however if it has more elements, 
# you need to specify a gradient argument that is a tensor of matching shape.

In [55]:
y.backward(gradients)

print(x.grad)

tensor([0.2000, 2.0000, 2.0000])


In [57]:
#You can also stop autograd from tracking history on Tensors with .
#requires_grad=True by wrapping the code block in with torch.no_grad()

In [236]:
x = torch.rand(2,2,requires_grad=True)

In [238]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# 在测试无需求梯度可以关闭
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


## 例子

In [2]:
import torch

In [254]:
# y = x * w
# z = y + b

#前向传播的过程

x = torch.rand(1)
w = torch.rand(1, requires_grad = True)
b = torch.rand(1, requires_grad = True)
# b_2 = torch.rand(2, requires_grad = True)
y = x * w
z = y + b
# z_2 = y * b_2
print('x is:', x)
print('w is:', w)
print('b is:', b)
print('y is:', y)
print('z is:', z)  #grad_fn：

x is: tensor([0.6498])
w is: tensor([0.3573], requires_grad=True)
b is: tensor([0.3834], requires_grad=True)
y is: tensor([0.2321], grad_fn=<MulBackward0>)
z is: tensor([0.6155], grad_fn=<AddBackward0>)


In [255]:
b_2 = torch.rand(2, requires_grad = True)

In [256]:
z_2 = y * b_2

In [257]:
z.backward(retain_graph=True)  

In [258]:
print(w.grad)

tensor([0.6498])


In [259]:
z_2

tensor([0.1673, 0.1720], grad_fn=<MulBackward0>)

In [109]:
b_2 = torch.rand(2, requires_grad = True)

In [110]:
z_2 = y * b_2

In [111]:
y

tensor([0.2177], grad_fn=<MulBackward0>)

In [260]:
z_2.sum().backward()

In [113]:
z.backward(retain_graph=True)  

In [114]:
print(w.grad) 

tensor([0.2460])


In [261]:
print(w.grad) 

tensor([1.5996])


In [115]:
w.grad.zero_()

tensor([0.])

In [116]:
print(w.grad)

tensor([0.])


In [117]:
gradients = torch.tensor([1,1], dtype=torch.float)

In [118]:
z_2.backward(gradients)

In [119]:
z_2

tensor([0.0499, 0.1304], grad_fn=<MulBackward0>)

In [79]:
print(w.grad) 

tensor([0.9567])


### torch.autograd.grad

In [3]:
# x/y dy/dx  backward()

x = torch.rand(1, 2, requires_grad = True)
y = torch.sum(x)
z = y + torch.Tensor([1,2])

In [15]:
x

tensor([[0.7464, 0.5645]], requires_grad=True)

In [14]:
y

tensor(1.3108, grad_fn=<SumBackward0>)

In [16]:
z

tensor([2.3108, 3.3108], grad_fn=<AddBackward0>)

In [9]:
z1 = z.sum()

In [265]:
# help(torch.autograd.grad)

In [269]:
# gradients = torch.tensor([1,1], dtype=torch.float)

In [271]:

grad = torch.autograd.grad(outputs=z1, inputs=x,retain_graph=True)

# print(grad)

In [272]:
grad

(tensor([[2., 2.]]),)

### torch.autograd.no_grad()

- 禁止梯度计算的上下文管理器
- 上下文管理器，禁用梯度计算。当您确信不会调用tensor.backward()时，禁用梯度计算对于推理非常有用。
它将减少计算的内存消耗。在这种模式下，即使输入requires_grad=True，每个计算的结果都将是requires_grad=False

In [273]:
x = torch.tensor([1.0], requires_grad = True)
y = x * 2

print(y.requires_grad)

with torch.autograd.no_grad():
    y = x * 2
    
print(y.requires_grad)

True
False


### torch.autograd.enable_grad()

- 启动梯度计算的上下文管理器

In [276]:
x = torch.tensor([1.0], requires_grad = True)

with torch.autograd.no_grad():
    y = x * 2
    print(y.requires_grad)
    with torch.autograd.enable_grad():
        y = x * 2
    
print(y.requires_grad)

False
True


### torch.autograd.set_grad_enabled

- 设置是否进行梯度计算的上下文管理器

In [96]:
x = torch.tensor([1.0], requires_grad = True)

with torch.autograd.set_grad_enabled(True):
    y = x * 2
print(y.requires_grad)


with torch.autograd.set_grad_enabled(False):
    y = x * 2
print(y.requires_grad)

True
False
