In [2]:
import torch

In [2]:
# 构造一个5x3矩阵，未初始化：

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[4.6837e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


In [4]:
# 获取tensor的大小
# torch.Size 实际上是一个元组，所以它支持相同的操作

In [4]:
x.size()

torch.Size([5, 3])

In [5]:
help(torch.rand)

Help on built-in function rand:

rand(...)
    rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
      

In [8]:
# torch.rand,Returns a tensor filled with random numbers from a uniform distribution

In [23]:
y = torch.rand(5, 3)

In [24]:
x= torch.rand(5, 3)

In [95]:
x

tensor([[0.2585, 0.7857, 0.2294],
        [0.2624, 0.1006, 0.2053],
        [0.3613, 0.6079, 0.5485],
        [0.8599, 0.0896, 0.4978],
        [0.0965, 0.9550, 0.2583]])

In [93]:
y

tensor([[0.5158, 0.5959, 0.1621],
        [0.3573, 0.4468, 0.5675],
        [0.5732, 0.3973, 0.1708],
        [0.3644, 0.3677, 0.5251],
        [0.7759, 0.6641, 0.5169]])

In [96]:
x+y

tensor([[0.7743, 1.3816, 0.3915],
        [0.6197, 0.5474, 0.7728],
        [0.9346, 1.0052, 0.7192],
        [1.2243, 0.4573, 1.0229],
        [0.8724, 1.6192, 0.7752]])

In [97]:
y.add_(x)
print(y)

tensor([[0.7743, 1.3816, 0.3915],
        [0.6197, 0.5474, 0.7728],
        [0.9346, 1.0052, 0.7192],
        [1.2243, 0.4573, 1.0229],
        [0.8724, 1.6192, 0.7752]])


In [16]:
# 将Tensor转换为numpy数组

In [102]:
y

tensor([[0.7743, 1.3816, 0.3915],
        [0.6197, 0.5474, 0.7728],
        [0.9346, 1.0052, 0.7192],
        [1.2243, 0.4573, 1.0229],
        [0.8724, 1.6192, 0.7752]])

In [103]:
y1 = y.numpy()

In [105]:
y.add_(1)

tensor([[1.7743, 2.3816, 1.3915],
        [1.6197, 1.5474, 1.7728],
        [1.9346, 2.0052, 1.7192],
        [2.2243, 1.4573, 2.0229],
        [1.8724, 2.6192, 1.7752]])

In [106]:
print(y1)

[[1.7742631 2.3816018 1.3914711]
 [1.6196917 1.5474147 1.7728198]
 [1.9345767 2.0051804 1.7192353]
 [2.2242694 1.4573026 2.022867 ]
 [1.8723872 2.6191833 1.7751737]]


In [20]:
# 将numpy数组转换为Torch张量

In [10]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [13]:
a1 = np.ones(5)
a1

array([1., 1., 1., 1., 1.])

In [15]:
b1 = torch.from_numpy(a1)
b1

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [7]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [16]:
np.add(a1, 1, out=a1)

array([2., 2., 2., 2., 2.])

In [17]:
a1

array([2., 2., 2., 2., 2.])

In [18]:
b1

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

> a1为array，b1为由a1转换而来的tensor，两者地址不同但是都是引用同一地址内的数据，所以一个修改另一个同时也修改了

In [20]:
print(id(a1))
print(id(b1))

2396476580448
2396476581752


In [21]:
# CUDA传感器
# 可以使用该.cuda功能将传感器移动到GPU上。

In [25]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [26]:
torch.cuda.is_available()

True

In [26]:
# 定义一个tensor

In [116]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


In [117]:
# 初始化一个全是1的tensor

a = torch.ones(2,5)

print(a)
print(a.type())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.FloatTensor


In [118]:
# 初始化一个全零的tensor
a = torch.zeros(3,3)

print(a)
print(a.type())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [29]:
# 初始化一个对角线为1的tensor

a = torch.eye(3,3)

print(a)
print(a.type())

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.FloatTensor


In [119]:
#定义一个与a形状相同的全零tensor

b = torch.zeros_like(a)

print(b)
print(b.type())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [120]:
#同上
b = torch.ones_like(a)

print(b)
print(b.type())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [27]:
help(torch.normal)

Help on built-in function normal:

normal(...)
    normal(mean, std, *, generator=None, out=None) -> Tensor
    
    Returns a tensor of random numbers drawn from separate normal distributions
    whose mean and standard deviation are given.
    
    The :attr:`mean` is a tensor with the mean of
    each output element's normal distribution
    
    The :attr:`std` is a tensor with the standard deviation of
    each output element's normal distribution
    
    The shapes of :attr:`mean` and :attr:`std` don't need to match, but the
    total number of elements in each tensor need to be the same.
    
    .. note:: When the shapes do not match, the shape of :attr:`mean`
              is used as the shape for the returned output tensor
    
    .. note:: When :attr:`std` is a CUDA tensor, this function synchronizes
              its device with the CPU.
    
    Args:
        mean (Tensor): the tensor of per-element means
        std (Tensor): the tensor of per-element standard deviation

In [122]:
a  = torch.normal(mean=0., std=5.,size=(1, 4))   

print(a)
print(a.type())

tensor([[ 4.1904, 14.6012, -1.7961,  3.5772]])
torch.FloatTensor


In [28]:
a = torch.Tensor([1, 2])
b = torch.Tensor([3, 4])

In [29]:
a

tensor([1., 2.])

In [30]:
b

tensor([3., 4.])

In [31]:
a + b

tensor([4., 6.])

In [32]:
a,b

(tensor([1., 2.]), tensor([3., 4.]))

In [33]:
a.add(b)

tensor([4., 6.])

In [34]:
a

tensor([1., 2.])

In [35]:
a.add_(b)

tensor([4., 6.])

In [36]:
a

tensor([4., 6.])

In [43]:
# 加法运算

c = a + b
c = torch.add(a, b)
c = a.add(b)
print(a)
c = a.add_(b) 
print(a)

tensor([1., 2.])
tensor([4., 6.])


In [44]:
# 减法
c = a - b
c = torch.sub(a, b)
c = a.sub(b)
print(c)
print(a)
c = a.sub_(b) 
print(c)
print(a)

tensor([1., 2.])
tensor([4., 6.])
tensor([1., 2.])
tensor([1., 2.])


In [45]:
# 乘法运算

a = torch.Tensor([1, 2])
b = torch.Tensor([3, 4])

c = a * b
c = torch.mul(a, b)
c = a.mul(b)
print(c)
c = a.mul_(b) 
print(c)

tensor([3., 8.])
tensor([3., 8.])


In [46]:
# 除法运算

a = torch.Tensor([1, 2])
b = torch.Tensor([3, 4])

c = a / b
c = torch.div(a, b)
c = a.div(b)
print(c)
c = a.div_(b) 
print(c)

tensor([0.3333, 0.5000])
tensor([0.3333, 0.5000])


In [47]:
# 矩阵运算 a*b ->(m,n)*(n,k)

a = torch.ones(2, 1)
b = torch.ones(1, 3)
print(a,b)

tensor([[1.],
        [1.]]) tensor([[1., 1., 1.]])


In [48]:
# a*b  

c = torch.mm(a, b)
c = torch.matmul(a, b)
print(c)
c = a @ b
c = a.matmul(b)
c = a.mm(b)

print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [49]:
# 幂运算

c = torch.pow(a, 2)
c = a.pow(2)
c = a**2
c = a.pow_(2)

print(c)

tensor([[1.],
        [1.]])


In [50]:
# e**n exp

c = torch.exp(a)
c = a.exp_()
print(c)

tensor([[2.7183],
        [2.7183]])


In [51]:
# 开方运算

c = a.sqrt()
c = a.sqrt_()

print(c)

tensor([[1.6487],
        [1.6487]])


In [52]:
# 对数运算

c = torch.log2(a)
c = torch.log10(a)
c = torch.log(a)
c = torch.log_(a)

print(c)

tensor([[0.5000],
        [0.5000]])


In [53]:
# torch.cat(seq, dim=0, out=None)：按照已经存在的维度进行拼接
# torch.stack(seq, dim=0, out=None)：按照新的维度进行拼接
#注: .cat 和 .stack的区别在于 cat会增加现有维度的值,可以理解为续接，stack会新加增加一个维度，可以

#理解为叠加

In [133]:
a = torch.zeros((2, 4))
b = torch.ones((2, 4))

In [134]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [135]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [136]:
torch.cat((a, b)) 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
# torch.cat

a = torch.zeros((2, 4))
b = torch.ones((2, 4))
print(a)
print(b)

out = torch.cat((a, b), dim=0) 
print(out)
print(out.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([4, 4])


In [55]:
out = torch.cat((a, b), dim=1) 
print(out)
print(out.shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])
torch.Size([2, 8])


In [142]:
torch.linspace(1, 9, 4).view(2, 2)

tensor([[1.0000, 3.6667],
        [6.3333, 9.0000]])

In [143]:
#torch.stack

a = torch.linspace(1, 9, 9).view(3, 3)
b = torch.linspace(10, 18, 9).view(3, 3)
print(a)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


In [147]:
help(torch.stack)

Help on built-in function stack:

stack(...)
    stack(tensors, dim=0, out=None) -> Tensor
    
    Concatenates sequence of tensors along a new dimension.
    
    All tensors need to be of the same size.
    
    Arguments:
        tensors (sequence of Tensors): sequence of tensors to concatenate
        dim (int): dimension to insert. Has to be between 0 and the number
            of dimensions of concatenated tensors (inclusive)
        out (Tensor, optional): the output tensor.



In [152]:
out = torch.stack((a, b),dim=2)

In [153]:
out.size()

torch.Size([3, 3, 2])

In [58]:
#torch.chunk(tensor, chunk_num, dim)与torch.cat()原理相反，它是将tensor按dim（行或列）分割成chunk_num个tensor块，返回的是一个元组。

In [173]:
a = torch.rand(3,3)

In [174]:
out = torch.chunk(a, 2)

In [175]:
out

(tensor([[0.1888, 0.9857, 0.3204],
         [0.3662, 0.4248, 0.0140]]),
 tensor([[0.0601, 0.1159, 0.0328]]))

In [177]:
a

tensor([[0.1888, 0.9857, 0.3204],
        [0.3662, 0.4248, 0.0140],
        [0.0601, 0.1159, 0.0328]])

In [178]:
out = torch.split(a, 2, dim=1)
print(len(out))
print(out[1], out[1].shape)

2
tensor([[0.3204],
        [0.0140],
        [0.0328]]) torch.Size([3, 1])


In [63]:
a = torch.rand(2, 3)
print(a)

tensor([[0.7087, 0.1431, 0.2755],
        [0.5715, 0.3302, 0.7011]])


In [179]:
a = torch.rand(6)

In [180]:
a

tensor([0.9693, 0.8277, 0.0830, 0.5431, 0.6596, 0.8729])

In [181]:
out = torch.reshape(a, (3, 2))
print(out)
print(out.shape)

tensor([[0.9693, 0.8277],
        [0.0830, 0.5431],
        [0.6596, 0.8729]])
torch.Size([3, 2])


In [182]:
# view
out = a.view(2, 3)
print(out)

tensor([[0.9693, 0.8277, 0.0830],
        [0.5431, 0.6596, 0.8729]])


In [184]:
a = torch.rand(4,5)

In [185]:
a

tensor([[0.0657, 0.7832, 0.3745, 0.3862, 0.4746],
        [0.6102, 0.6137, 0.5335, 0.6711, 0.5053],
        [0.8901, 0.7022, 0.2508, 0.1964, 0.6914],
        [0.3348, 0.3137, 0.8108, 0.7413, 0.9831]])

In [186]:
a.view(5,4)

tensor([[0.0657, 0.7832, 0.3745, 0.3862],
        [0.4746, 0.6102, 0.6137, 0.5335],
        [0.6711, 0.5053, 0.8901, 0.7022],
        [0.2508, 0.1964, 0.6914, 0.3348],
        [0.3137, 0.8108, 0.7413, 0.9831]])

In [187]:
a = torch.rand(3,2)

In [188]:
a

tensor([[0.0532, 0.7442],
        [0.7235, 0.7221],
        [0.4225, 0.5245]])

In [190]:
# torch.transpose 交换2个维度

# print(out) #(3, 2)
out1 = torch.transpose(a, 0, 1)
print(out1)

tensor([[0.0532, 0.7235, 0.4225],
        [0.7442, 0.7221, 0.5245]])


In [191]:
y = torch.rand(2,3,4)

In [192]:
y

tensor([[[0.9586, 0.1505, 0.3778, 0.7283],
         [0.4943, 0.3782, 0.0803, 0.5561],
         [0.9147, 0.5137, 0.0971, 0.1968]],

        [[0.2604, 0.8164, 0.5302, 0.2788],
         [0.7760, 0.6747, 0.4669, 0.7376],
         [0.3537, 0.7980, 0.1327, 0.1288]]])

In [194]:
help(torch.transpose)

Help on built-in function transpose:

transpose(...)
    transpose(input, dim0, dim1) -> Tensor
    
    Returns a tensor that is a transposed version of :attr:`input`.
    The given dimensions :attr:`dim0` and :attr:`dim1` are swapped.
    
    The resulting :attr:`out` tensor shares it's underlying storage with the
    :attr:`input` tensor, so changing the content of one would change the content
    of the other.
    
    Args:
        input (Tensor): the input tensor.
        dim0 (int): the first dimension to be transposed
        dim1 (int): the second dimension to be transposed
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 1.0028, -0.9893,  0.5809],
                [-0.1669,  0.7299,  0.4942]])
        >>> torch.transpose(x, 0, 1)
        tensor([[ 1.0028, -0.1669],
                [-0.9893,  0.7299],
                [ 0.5809,  0.4942]])



In [196]:
help(y.permute)

Help on built-in function permute:

permute(...) method of torch.Tensor instance
    permute(*dims) -> Tensor
    
    Returns a view of the original tensor with its dimensions permuted.
    
    Args:
        *dims (int...): The desired ordering of dimensions
    
    Example:
        >>> x = torch.randn(2, 3, 5)
        >>> x.size()
        torch.Size([2, 3, 5])
        >>> x.permute(2, 0, 1).size()
        torch.Size([5, 2, 3])



In [40]:
# y.permute(2,1,0)

In [38]:
help(torch.full)

Help on built-in function full:

full(...)
    full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Creates a tensor of size :attr:`size` filled with :attr:`fill_value`. The
    tensor's dtype is inferred from :attr:`fill_value`.
    
    Args:
        size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
            shape of the output tensor.
        fill_value (Scalar): the value to fill the output tensor with.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
     

In [200]:
out = torch.full((4, 5), 20.)
print(out)

tensor([[20., 20., 20., 20., 20.],
        [20., 20., 20., 20., 20.],
        [20., 20., 20., 20., 20.],
        [20., 20., 20., 20., 20.]])
