In [2]:
import numpy as np
import torch

In [5]:
arr = np.ones((3, 3))
print("ndarray的数据类型：", arr.dtype)

ndarray的数据类型： float64


## 从data创建tensor

In [6]:
t = torch.tensor(arr)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [4]:
t = torch.tensor(arr, device='cuda')   # 使用GPU，从CPU转GPU有一定的耗时
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)

## 从numpy创建tensor

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
t = torch.from_numpy(arr)
print("numpy array:", arr)
print("tensor:", t)

numpy array: [[1 2 3]
 [4 5 6]]
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [9]:
# 共享内存，当修改一个数据，另一个也将会被改动
print("\n修改arr")
arr[0, 0] = 0
print("numpy array:", arr)
print("tensor:", t)


修改arr
numpy array: [[0 2 3]
 [4 5 6]]
tensor: tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [10]:
print("\n修改tensor")
t[0, 0] = -1
print("numpy array:", arr)
print("tensor:", t)


修改tensor
numpy array: [[-1  2  3]
 [ 4  5  6]]
tensor: tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## 全零张量

In [5]:
out_t = torch.tensor([1])

print(id(out_t))

t = torch.zeros((3, 3), out=out_t)   # t和out_t地址一致，同一数据不同名称

print(t, '\n', out_t)
print(id(t), id(out_t), id(t) == id(out_t))

2123859465304
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
2123859465304 2123859465304 True


## 创建给定形状的全部为指定值的张量

In [6]:
t = torch.full((3, 3), 1)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 创建等差数列张量

In [7]:
t = torch.arange(2, 10, 2)
print(t)

tensor([2, 4, 6, 8])


## 创建均分数列张量

In [8]:
t = torch.linspace(2, 10, 6)   # 从2到10，共生成六个数字
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


## 设置均值和标准差的正态分布

In [10]:
# mean:张量  std:张量
mean = torch.arange(1, 5, dtype=torch.float )
std = torch.arange(1, 5, dtype=torch.float )
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([0.5549, 0.5847, 5.6844, 9.5147])


In [12]:
# mean:标量  std:标量
t_normal = torch.normal(0., 1., size=(4,))

print("mean:{}\nstd:{}".format(mean,std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([-0.5465, -0.0733, -1.5962,  0.0534])


In [13]:
# mean:张量  std:标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean,std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:1
tensor([1.4067, 2.5392, 2.9900, 4.1529])
