In [18]:
import torch

# torch.nn构建神经网络
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

<img src="image/1.png" width="450" heigth="230">

> 上图中表示的是四句话的前两个单词的词向量

In [21]:
# n_inputs每个输入样本的x(i)的维度，比如一句话的一个词用多少维表示
# n_neurons：隐藏层的神经单元的个数
# 在这个例子中，每句话有2个词。

In [22]:
class SingleRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(SingleRNN, self).__init__()
        
        self.Wx = torch.randn(n_inputs, n_neurons) # 4 X 1
        self.Wy = torch.randn(n_neurons, n_neurons) # 1 X 1
        
        self.b = torch.zeros(1, n_neurons) # 1 X 1
    
    def forward(self, X0, X1):
        self.Y0 = torch.tanh(torch.mm(X0, self.Wx) + self.b) # 4 X 1
        
        self.Y1 = torch.tanh(torch.mm(self.Y0, self.Wy) +
                            torch.mm(X1, self.Wx) + self.b) # 4 X 1
        
        return self.Y0, self.Y1

In [23]:
N_INPUT = 4
N_NEURONS = 1

X0_batch = torch.tensor([[0,1,2,0], [3,4,5,0], 
                         [6,7,8,0], [9,0,1,0]],
                        dtype = torch.float) #t=0 => 4 X 4#4个样本的x0，每个x0用4维表示

X1_batch = torch.tensor([[9,8,7,0], [0,0,0,0], 
                         [6,5,4,0], [3,2,1,0]],
                        dtype = torch.float) #t=1 => 4 X 4

model = SingleRNN(N_INPUT, N_NEURONS)

Y0_val, Y1_val = model(X0_batch, X1_batch)

In [25]:
Y1_val

tensor([[-0.9923],
        [ 0.9272],
        [-0.2116],
        [-0.7318]])

In [24]:
Y0_val

tensor([[-0.9971],
        [-1.0000],
        [-1.0000],
        [ 1.0000]])

<img src="image/2.png" width="850" heigth="230">

In [26]:
class BasicRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(BasicRNN, self).__init__()
        
        self.Wx = torch.randn(n_inputs, n_neurons) # n_inputs X n_neurons
        self.Wy = torch.randn(n_neurons, n_neurons) # n_neurons X n_neurons
        
        self.b = torch.zeros(1, n_neurons) # 1 X n_neurons
    
    def forward(self, X0, X1):
        self.Y0 = torch.tanh(torch.mm(X0, self.Wx) + self.b) # batch_size X n_neurons
        
        self.Y1 = torch.tanh(torch.mm(self.Y0, self.Wy) +
                            torch.mm(X1, self.Wx) + self.b) # batch_size X n_neurons
        
        return self.Y0, self.Y1

In [28]:
N_INPUT = 3 # number of features in input
N_NEURONS = 5 # number of units in layer

X0_batch = torch.tensor([[0,1,2], [3,4,5], 
                         [6,7,8], [9,0,1]],
                        dtype = torch.float) #t=0 => 4 X 3

X1_batch = torch.tensor([[9,8,7], [0,0,0], 
                         [6,5,4], [3,2,1]],
                        dtype = torch.float) #t=1 => 4 X 3

model = BasicRNN(N_INPUT, N_NEURONS)

Y0_val, Y1_val = model(X0_batch, X1_batch)

In [29]:
Y0_val

tensor([[-0.9131, -0.7210,  0.9885,  0.9834,  0.8200],
        [-0.9957,  0.9116,  1.0000,  1.0000, -0.9987],
        [-0.9998,  0.9993,  1.0000,  1.0000, -1.0000],
        [ 1.0000,  0.9999,  0.4377,  1.0000, -1.0000]])

In [30]:
Y1_val

tensor([[-0.9173,  1.0000,  1.0000,  1.0000, -1.0000],
        [ 0.1294,  0.9119,  0.1626,  0.9556,  0.5013],
        [-0.8654,  1.0000,  1.0000,  1.0000, -1.0000],
        [-0.9927,  0.9999,  0.9615,  1.0000, -1.0000]])