In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
print(np.__version__)

1.20.1


- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float # 复数/实数  2+i. i^2=-1 
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [6]:
arr = np.array([1, 2, 3, 4], dtype="i8")

print(arr.dtype)

int64


# 复制与视图

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# copy()是形成新的数组，不影响原数组
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

# 原数组改变，视图同样改变
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
import numpy as np

# 改变视图原数组也被改变
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# 维度中有且仅有一个可以-1，这个维度会随着其他固定维度自动计算
newarr = arr.reshape(-1,2,3)

In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print(arr)


# 数组元素展开
newarr = arr.reshape(-1)
# newarr = arr.flatten()

print(newarr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)


# 拼接

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# concatenate: 拼接，默认是行上拼接，可以通过axis设置
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [14]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print()
print(arr2)
print()
print(np.concatenate((arr1, arr2)))
print()
print(np.concatenate((arr1, arr2, arr1), axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6 1 2]
 [3 4 7 8 3 4]]


In [15]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

print (np.stack((arr1, arr2), axis=1))
print (np.stack((arr1, arr2), axis=0))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2)) # hstack: horizontal

print(arr)

[1 2 3 4 5 6]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2)) # vstack: vertical

print(arr)

[[1 2 3]
 [4 5 6]]


# 执值寻位

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [19]:
import numpy as np

arr = np.array([3, 2, 0, 1, 1])

print(np.sort(arr)) # "quicksort"，默认快速排序

[0 1 1 2 3]


In [20]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])


print (arr)
print ()

# 列上比较，较小的前一行，较大的后一行
print(np.sort(arr, axis=0))

# 行上比较，每行从小到大
print(np.sort(arr, axis=1))

[[3 2 4]
 [5 0 1]]

[[3 0 1]
 [5 2 4]]
[[2 3 4]
 [0 1 5]]


# 过滤

In [21]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# filter_arr存放判断条件
filter_arr = [True, False, True, False]

# 通过filter_arr列表中的值对应arr中的值输出
newarr = arr[filter_arr]

print(newarr)

[41 43]
