In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = [] # z=[5,7,9,11]

# 使用zip将x，y打包
for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


- add 加
- subtract 减
- multiply 对应位置相乘
- divide 除
- power 乘幂
- absolute 绝对值
- floor 向下取整
- ceil 向上取整
- log、log2、log10 有些需要用换底公式，默认为e

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2, arr1, arr1, arr2])

print(newarr)

30


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

# 每行上面各自相加
newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# 逐元素相加
newarr = np.cumsum(arr)  # cumulative  sum

print(newarr)

[ 1  3  6 10 15]


In [6]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

b= np.array([10, 20, 30])
print (a.shape, b.shape)
print()
print("A =", a)
print()
print("b =", b)
print()
# 矩阵相乘
print("Ab =",np.matmul(a,b)) # matrix multiplication

(3, 3) (3,)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]

b = [10 20 30]

Ab = [140 320 500]


In [7]:
import numpy as np

np.random.seed(2)

# 构建0-15之间整数，形状为（3,2）的矩阵
A = np.random.randint(0, 15, size=(3,2))

print("Matrix A:\n", A)
print("shape of A =", A.shape)

Matrix A:
 [[ 8 13]
 [ 8  6]
 [11  2]]
shape of A = (3, 2)


In [ ]:
x = np.random.randint(0,256, size=(1000,10000)).astype("float64")

# 统计用时

In [ ]:
import time

tic = time.time()  # start time



toc = time.time()   # finish time

time_taken = toc - tic #time in s  finsih time - start time