# randint()

In [3]:
from numpy import random

# 0-99整数，10个元素的向量
x=random.randint(100, size=(10))

x

array([21, 10, 34, 41, 64, 10, 11, 78, 16, 41])

# rand()

In [4]:
from numpy import random

# 生成5个（0,1）数
x = random.rand(5) # random generator for float (0,1)

print(x)

[0.88383595 0.66396503 0.59350756 0.90633841 0.10397972]


# choice()

In [7]:
from numpy import random
# 给定每个值被选中的概率，从这个数字中采样数字： multinomial distribution
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,5))

print(x)

[[5 7 7 7 5]
 [5 7 3 7 5]
 [7 7 7 5 7]]


# shuffle()原地随机重排

In [1]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 4 5 1 3]


# permutation()返回一个重新排列的数组(并且保持原始数组不变)

In [2]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[1 2 4 5 3]


# normal()正态分布

In [3]:
from numpy import random

# loc均值，scale标准差
x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[-1.27884932  5.25260773 -2.36879501]
 [ 0.28987986 -0.71863965  1.13656522]]
