#### What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.



In [27]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = [] # z=[5,7,9,11]

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [28]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [3]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [29]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [30]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [6]:
# The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [31]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [32]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [10]:
#### rounding
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [11]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


### log的应用

In [33]:
import numpy as np

arr = np.arange(1, 10)
print(arr)

print(np.log2(arr))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [1]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

# print (np.log7(arr))  # ”log的换底公式“

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [14]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr)) # default: e. 2.7xxxx

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### sum
Addition is done between two arguments whereas summation happens over n elements.


In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2, arr1, arr1, arr2])

print(newarr)

30


In [39]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [42]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [43]:
import numpy as np

arr = np.array([1, 2, 3,4,5])

newarr = np.cumsum(arr)  # cumulative  sum

print(newarr)

[ 1  3  6 10 15]


In [45]:
#### matrix multiplication
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

b= np.array([10, 20, 30])
print (a.shape, b.shape)

print("A =", a)

print("b =", b)

print("Ab =",np.matmul(a,b)) # matrix multiplication

(3, 3) (3,)
A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [10 20 30]
Ab = [140 320 500]


In [62]:
import numpy as np

np.random.seed(2)

A = np.random.randint(0, 15, size=(3,2))
B = np.random.randint(0, 15, size =(2,4))

print("Matrix A:\n", A)
print("shape of A =", A.shape)
print()
print("Matrix B:\n", B)
print("shape of B =", B.shape)

Matrix A:
 [[ 8 13]
 [ 8  6]
 [11  2]]
shape of A = (3, 2)

Matrix B:
 [[11  8  7  2]
 [ 1 11  5 10]]
shape of B = (2, 4)


In [63]:
C = np.matmul(A, B)

print("product of A and B:\n", C)

print("shape of product =", C.shape)

product of A and B:
 [[101 207 121 146]
 [ 94 130  86  76]
 [123 110  87  42]]
shape of product = (3, 4)


In [65]:
import numpy as np

np.random.seed(42)

A = np.random.randint(0, 10, size=(2,2))

B = np.random.randint(0, 10, size=(2,3))

C = np.random.randint(0, 10, size=(3,3))

print("Matrix A:\n{}, shape={}\n".format(A, A.shape))

print("Matrix B:\n{}, shape={}\n".format(B, B.shape))

print("Matrix C:\n{}, shape={}\n".format(C, C.shape))

Matrix A:
[[6 3]
 [7 4]], shape=(2, 2)

Matrix B:
[[6 9 2]
 [6 7 4]], shape=(2, 3)

Matrix C:
[[3 7 7]
 [2 5 4]
 [1 7 5]], shape=(3, 3)



In [66]:
# 矩阵乘法里，相乘的顺序不影响最终的结果，但是营销计算效率
# 算法导论：动态规划里面的一个算法案例：matrix multiplication
# (A*B)*C

D = np.matmul(np.matmul(A,B), C)

print("Result of multiplication in the order (AB)C:\n\n{},shape={}\n".format(D, D.shape))

# A*(B*C)
D = np.matmul(A, np.matmul(B,C))

print("Result of multiplication in the order A(BC):\n\n{},shape={}".format(D, D.shape))

Result of multiplication in the order (AB)C:

[[ 336  921  798]
 [ 410 1127  976]],shape=(2, 3)

Result of multiplication in the order A(BC):

[[ 336  921  798]
 [ 410 1127  976]],shape=(2, 3)


#### Element-wise matrix multiplication


In [68]:
import numpy as np

np.random.seed(42)

A = np.random.randint(0, 10, size=(3,3))

B = np.random.randint(0, 10, size=(3,3))

print("Matrix A:\n{}\n".format(A))

print("Matrix B:\n{}\n".format(B))

C = np.multiply(A,B) # or A * B   different from matmul()

print("Element-wise multiplication of A and B:\n{}".format(C))

Matrix A:
[[6 3 7]
 [4 6 9]
 [2 6 7]]

Matrix B:
[[4 3 7]
 [7 2 5]
 [4 1 7]]

Element-wise multiplication of A and B:
[[24  9 49]
 [28 12 45]
 [ 8  6 49]]


In [69]:
import numpy as np

np.random.seed(42)

A = np.random.randint(0, 10, size=(3,4))

B = np.array([[1,2,3,4]])

print("Matrix A:\n{}, shape={}\n".format(A, A.shape))

print("Matrix B:\n{}, shape={}\n".format(B, B.shape))

C = A * B

print("Element-wise multiplication of A and B:\n{}".format(C))

Matrix A:
[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]], shape=(3, 4)

Matrix B:
[[1 2 3 4]], shape=(1, 4)

Element-wise multiplication of A and B:
[[ 6  6 21 16]
 [ 6 18  6 24]
 [ 7  8  9 28]]


In [72]:
import numpy as np

import time

# generating 1000 x 1000 matrices
np.random.seed(42)

x = np.random.randint(0,256, size=(1000,10000)).astype("float64")

y = np.random.randint(0,256, size=(10000,1000)).astype("float64")


#computing multiplication time on CPU
tic = time.time()  # start time

z = np.matmul(x,y)

toc = time.time()   # finish time

time_taken = toc - tic #time in s  finsih time - start time

print("Time taken on CPU (in ms) = {}".format(time_taken*1000))

Time taken on CPU (in ms) = 199.1558074951172
